services:
  cpmynav:
    build: .
    image: cunpeng/cpmynav:1.1
    platform: linux/arm64  # 支持ARM64架构，如需AMD64改为 linux/amd64
    ports:
      - "8821:80"
    volumes:
      - cpmynav_data:/data
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    container_name: cpmynav_app

volumes:
  cpmynav_data: