name: Build and Push Multi-Arch Image

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: cpmynav             # 只写镜像名
  DOCKERHUB_USERNAME: cunpeng

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5   # 升级到 v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4   # 升级到 v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4   # 升级到 v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4   # 升级到 v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v7   # 升级到 v7
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:1.1
